#!/bin/bash

expname="0"
histno=3
varnames="FRONTGF,FRONTGFA"
levind="48,"
y1=0001
y2=0005
#mon_opt=0
  # 0,1,2,3,4 - Annual, DJF, MAM, JJA, SON
#--------------------------------------------
for mon_opt in {1..4} ; do
#--------------------------------------------
ftail=( ann djf mam jja son )
outfname="ws_xyz.${ftail[$mon_opt]}.$y1-$y2.exp$expname"

mon=( 01 02 03 04 05 06 07 08 09 10 11 12 )
[ $mon_opt -eq 1 ] && mon=( 01 02 12 )
[ $mon_opt -eq 2 ] && mon=( 03 04 05 )
[ $mon_opt -eq 3 ] && mon=( 06 07 08 )
[ $mon_opt -eq 4 ] && mon=( 09 10 11 )

dir="dat$expname"
files=( )

y=$(( y1 ))
while [ $y -le $(( y2 )) ] ; do
  yyyy="$y"
  [ $y -lt 1000 ] && yyyy="0$yyyy"
  [ $y -lt 100  ] && yyyy="0$yyyy"
  [ $y -lt 10   ] && yyyy="0$yyyy"
  for mm in ${mon[@]} ; do
    for ff in $dir/*.cam2.h$histno.$yyyy-$mm-*.nc ; do
      ff2=tmp/ws.$( basename $ff )
      rm -f $ff2
      ncap2 -h -v -s 'WS=sqrt((U^2)+(V^2))' $ff -o $ff2
      ncatted -h -O -a long_name,WS,m,c,'Horizontal wind speed' $ff2
      ncra -h -d lev,$levind $ff2 -O $ff2
      files=( "${files[@]}" $ff2 )
    done
  done
  y=$(( y + 1 ))
done
echo ${files[@]}

ncra -h -v $varnames ${files[@]} -o $outfname.nc

#--------------------------------------------
done  #mon_opt
#--------------------------------------------

