C   IMSL ROUTINE NAME   - UHELP2
C
C-----------------------------------------------------------------------
C
C   LATEST REVISION     - JANUARY 1, 1978
C
C   PURPOSE             - WRITE INFORMATION REGARDING IMSL INPUT
C                           AND OUTPUT CONVENTIONS
C
C   USAGE               - CALL UHELP2
C
C   REQD. IMSL ROUTINES - UGETIO
C
C   NOTATION            - INFORMATION ON SPECIAL NOTATION AND
C                           CONVENTIONS IS AVAILABLE IN THE MANUAL
C                           INTRODUCTION OR THROUGH IMSL ROUTINE UHELP
C
C   REMARKS      IF THE USER DESIRES THAT OUTPUT BE WRITTEN TO A DEVICE
C                OTHER THAN THE STANDARD OUTPUT DEVICE, HE MUST FIRST
C                CALL IMSL ROUTINE UGETIO TO RESET THE OUTPUT DEVICE.
C                SEE THE UGETIO DOCUMENT.
C
C-----------------------------------------------------------------------
C
      SUBROUTINE UHELP2
C                                  SPECIFICATIONS FOR LOCAL VARIABLES
      INTEGER            IOPT,NIN,NOUT
C                                  FIRST EXECUTABLE STATEMENT
      IOPT = 1
      CALL UGETIO (IOPT,NIN,NOUT)
      WRITE(NOUT,5)
    5 FORMAT(22X,24HINPUT/OUTPUT CONVENTIONS,//, 1X,64HALL IMSL SUBROUTI
     *NES, EXCEPT SOME OF THOSE IN CHAPTER U, ARE    ,/, 1X,63HINPUT/OUT
     *PUT FREE. EACH OF THE CHAPTER U ROUTINES THAT PERFORMS,/, 1X,64HIN
     *PUT AND/OR OUTPUT OPERATIONS CALLS SUBROUTINE UGETIO TO OBTAIN, /,
     * 1X,63HTHE CURRENT UNIT IDENTIFIER VALUES. UGETIO MAY BE CALLED BY
     * THE,/, 1X,64HUSER TO SET NEW VALUES FOR UNIT IDENTIFIERS AND THIS
     * CAUSES ALL ,/, 1X,67HSUBSEQUENT INPUT/OUTPUT BY OTHER IMSL ROUTIN
     *ES TO BE PERFORMED ON  ,/,1X,63HTHE NEW UNITS. DETAILS ARE GIVEN I
     *N THE UGETIO DOCUMENT.       )
      RETURN
      END

