C   IMSL ROUTINE NAME   - UHELP3
C
C-----------------------------------------------------------------------
C
C   LATEST REVISION     - JANUARY 1, 1978
C
C   PURPOSE             - WRITE INFORMATION REGARDING IMSL ERROR
C                           DETECTING FACILITIES
C
C   USAGE               - CALL UHELP3
C
C   REQD. IMSL ROUTINES - UGETIO
C
C   NOTATION            - INFORMATION ON SPECIAL NOTATION AND
C                           CONVENTIONS IS AVAILABLE IN THE MANUAL
C                           INTRODUCTION OR THROUGH IMSL ROUTINE UHELP
C
C   REMARKS      IF THE USER DESIRES THAT OUTPUT BE WRITTEN TO A DEVICE
C                OTHER THAN THE STANDARD OUTPUT DEVICE, HE MUST FIRST
C                CALL IMSL ROUTINE UGETIO TO SET THE OUTPUT DEVICE.
C                SEE THE UGETIO DOCUMENT.
C
C-----------------------------------------------------------------------
C
      SUBROUTINE UHELP3
C                                  SPECIFICATIONS FOR LOCAL VARIABLES
      INTEGER            IOPT,NIN,NOUT
C                                  SPECIFICATIONS FOR ARGUMENTS
C                                  SPECIFICATIONS FOR LOCAL VARIABLES
C                                  FIRST EXECUTABLE STATEMENT
      IOPT = 1
      CALL UGETIO (IOPT,NIN,NOUT)
      WRITE(NOUT,5)
    5 FORMAT(22X,26HERROR DETECTING FACILITIES,//,1X,64HMOST IMSL SUBROU
     *TINES HAVE AS THEIR LAST ARGUMENT AN ERROR PARA-,/,1X,64HMETER NAM
     *ED IER. WHEN ERRORS ARE DETECTED BY THE SUBROUTINE,    ,/,1X,64HIE
     *R IS SET TO THE APPROPRIATE VALUE (AS NOTED IN THE DOCUMENT)  ,/,1
     *X,64HAND RETURNED TO THE CALLING PROGRAM. IF IER IS RETURNED AS ZE
     *RO,,/,1X,25HNO ERRORS WERE DETECTED. )
      WRITE (NOUT,10)
   10 FORMAT(1X,/,1X,64HAN ADDITIONAL ERROR PARAMETER, INFER, MAY ALSO A
     *PPEAR IN THE    ,/,1X,64HARGUMENT LIST OF IMSL LIBRARY ROUTINES. T
     *HIS PARAMETER CONTAINS ,/,1X,64HADDITIONAL ERROR INFORMATION (IF R
     *EQUIRED) AND MAY EITHER BE AN ,/,1X, 64HARRAY OR SCALAR, DEPENDING
     * UPON ITS USE. INFER PRECEDES IER IN  ,/,1X,18HTHE ARGUMENT LIST.)
      WRITE (NOUT,15)
   15 FORMAT( 1X,/,1X,65HTHE UTILITY FUNCTIONS CHAPTER OF THE IMSL LIBRA
     *RY CONTAINS A SUB-,/,1X,64HROUTINE NAMED UERTST. THIS ROUTINE IS R
     *EFERENCED BY MOST IMSL   ,/, 1X,64HROUTINES AND HAS THE RESPONSIBI
     *LITY OF PRINTING APPROPRIATE     ,/, 1X,22HMESSAGES WHEN CALLED. ,
     *//,  1X,64HUERTST RECOGNIZES THREE SEVERITY LEVELS OF ERRORS ACCOR
     *DING TO  ,/, 1X,37HTHE VALUE OF ITS INPUT ARGUMENT IER. ,//)
      WRITE (NOUT,20)
   20 FORMAT(  1X,65H(1)  WARNING ERRORS - THESE ERRORS CAUTION THE USER
     * THAT - DURING,/,1X,64H     THE COURSE OF COMPUTATIONS - CERTAIN C
     *RITICAL CONDITIONS   ,/, 1X,64H     WERE DETECTED. THESE ERRORS AR
     *E NOT SO SEVERE AS TO SUS-   ,/, 1X,54H     PEND FURTHER COMPUTATI
     *ONS. (32 .LT. IER .LE. 64) ,//, 1X,64H(2)  WARNING ERRORS (WITH FI
     *X) - THESE NOTE MORE SEVERE ERROR   ,/, 1X,64H     TYPES. SOME ATT
     *EMPT HAS BEEN MADE TO CORRECT THE SITUATION ,/, 1X,60H     AND COM
     *PUTATIONS ARE CONTINUED. (64 .LT. IER .LE. 128) )
      WRITE (NOUT,25)
   25 FORMAT( 1X, /, 1X,64H(3)  TERMINAL ERRORS - ERRORS OF THIS SEVERIT
     *Y LEVEL ARE OF A   ,/,1X,64H     CRITICAL NATURE. ONCE AN ERROR OF
     * THIS TYPE IS DISCOVERED, ,/, 1X, 64H     FURTHER COMPUTATIONS ARE
     * DISCONTINUED. (128 .LT. IER)          ,//,1X,64HERRORS WHICH CANN
     *OT BE DETECTED, BUT WHICH ARE KNOWN TO BE POS- ,/, 1X,66HSIBLE, AR
     *E NOTED IN THE DOCUMENTATION OF THE SPECIFIC SUBROUTINES.)
      WRITE (NOUT,30)
   30 FORMAT(1X,//,1X,64HIF ANY ONE OF THE THREE ERROR TYPES MENTIONED A
     *BOVE IS DETECTED ,/,1X,64HDURING COMPUTATION WITHIN AN IMSL ROUTIN
     *E, IER IS SET TO THE    ,/,1X,65HAPPROPRIATE VALUE AND A CALL IS M
     *ADE TO UERTST FROM THAT ROUTINE.,/,1X,64HUERTST PRINTS A MESSAGE G
     *IVING THE NAME OF THE CALLING ROUTINE  ,/,1X,42HAND THE VALUE OF T
     *HE ERROR PARAMETER IER. ,//,1X,64HANOTHER ROUTINE, NAMED UERSET, A
     *LLOWS THE USER TO SELECTIVELY   ,/,1X,63HELIMINATE THE PRINTING OF
     * MESSAGES BY UERTST. DETAILS ARE GIVEN )
      WRITE (NOUT,35)
   35 FORMAT(1X,64HIN THE UERSET DOCUMENT. IN ORDER TO ELIMINATE ALL MES
     *SAGE PRINT-,/,1X,64HING BY UERTST FOR AN ENTIRE RUN, ONE SIMPLY PL
     *ACES THE FOLLOWING,/, 1X,48HSTATEMENT AT THE BEGINNING OF THE MAIN
     * PROGRAM, ,//,1X,33H          CALL UERSET (0,LEVOLD) ,//,1X,64HTHE
     * USER MAY ALSO WRITE A REPLACEMENT ROUTINE NAMED UERTST (WITH,/,1X
     *, 62HTWO ARGUMENTS AS DESCRIBED IN THE UERTST DOCUMENT) WHICH DOES
     * ,/,1X,64HPRINTING AND OTHER BOOKKEEPING AS NEEDED FOR A PARTICULA
     *R APPLI-,/,1X,8HCATION. )
      RETURN
      END

