C   IMSL ROUTINE NAME   - UHELP4
C
C-----------------------------------------------------------------------
C
C   LATEST REVISION     - JANUARY 1, 1978
C
C   PURPOSE             - WRITE INFORMATION REGARDING MATRIX/VECTOR
C                           STORAGE MODES USED IN IMSL SUBROUTINES
C
C   USAGE               - CALL UHELP4
C
C   REQD. IMSL ROUTINES - UGETIO
C
C   NOTATION            - INFORMATION ON SPECIAL NOTATION AND
C                           CONVENTIONS IS AVAILABLE IN THE MANUAL
C                           INTRODUCTION OR THROUGH IMSL ROUTINE UHELP
C
C   REMARKS      IF THE USER DESIRES THAT OUTPUT BE WRITTEN TO A DEVICE
C                OTHER THAN THE STANDARD OUTPUT DEVICE, HE MUST FIRST
C                CALL IMSL ROUTINE UGETIO TO RESET THE OUTPUT DEVICE.
C                SEE THE UGETIO DOCUMENT.
C
C-----------------------------------------------------------------------
C
      SUBROUTINE UHELP4
C                                  SPECIFICATIONS FOR LOCAL VARIABLES
      INTEGER            IOPT,NIN,NOUT
C                                  FIRST EXECUTABLE STATEMENT
      IOPT = 1
      CALL UGETIO (IOPT,NIN,NOUT)
      WRITE(NOUT,5)
    5 FORMAT(20X,27HMATRIX/VECTOR STORAGE MODES,//,  1X,65HMANY OF THE I
     *MSL LIBRARY ROUTINES DEAL WITH MATRICES AND VECTORS.,/, 1X,64HUSER
     *S SHOULD BE FAMILIAR WITH THE MANNER IN WHICH THESE ENTITIES,/, 1X
     *, 65HARE DECLARED AND MANIPULATED IN FORTRAN. AN ENVIRONMENT SPECI
     *FIC ,/, 1X,64HFORTRAN REFERENCE MANUAL PROVIDES THE NECESSARY INFO
     *RMATION. IT ,/, 1X,64HIS THE PURPOSE OF THIS SECTION TO GIVE A BRI
     *EF INTRODUCTION TO  ,/, 1X,64HTHIS TOPIC AND TO DEFINE OTHER STORA
     *GE MODES USED BY IMSL SUB-  ,/, 1X,10HROUTINES. )
      WRITE (NOUT,10)
   10 FORMAT( 1X, /,1X,17HFULL STORAGE MODE,//, 1X,64HTHE TERM VECTOR RE
     *FERS TO A FORTRAN ARRAY WITH ONE DIMENSION    ,/, 1X,64HAND MATRIX
     * REFERS TO AN ARRAY WITH TWO DIMENSIONS. FORTRAN      ,/, 1X,64HAR
     *RAYS OCCUPY A CONSECUTIVE SEQUENCE OF MEMORY LOCATIONS. A      ,/,
     * 1X,63HVECTOR V OF LENGTH 10 OCCUPIES TEN MEMORY LOCATIONS, REFERR
     *ED  ,/, 1X,63HTO AS V(1),V(2),...,V(10). V MAY BE DECLARED IN A FO
     *RTRAN      ,/,1X,45HPROGRAM IN A DIMENSION STATEMENT AS FOLLOWS. ,
     *//, 20X,18HDIMENSION V(10)   ,/)
      WRITE (NOUT,15)
   15 FORMAT(1X,64HMATRICES ARE DECLARED IN A SIMILAR MANNER, BUT TWO DI
     *MENSION    ,/,1X,63HBOUNDS ARE USED. FOR EXAMPLE, A 10 BY 20 MATRI
     *X NAMED A IS     ,/,1X,21HDECLARED AS FOLLOWS. ,//,20X,18HDIMENSIO
     *N A(10,20),//,1X,64HTHE NUMBER 10 IS THE FIRST DIMENSION BOUND AND
     * 20 IS THE SECOND.,/,1X,64HTHIS DECLARES A SEQUENCE OF 200 CONSECU
     *TIVE MEMORY LOCATIONS    ,/,1X,64HTHAT ARE REFERRED TO AS A(1,1),A
     *(2,1),...,A(10,1),A(1,2),       ,/,1X,64HA(2,2),...,A(10,2),...,A(
     *1,20),A(2,20),...,A(10,20) (I.E.,      ,/,1X,64HMATRICES ARE STORE
     *D BY COLUMNS.) IMSL DOCUMENTS REFER TO THIS   ,/,1X,25HAS * FULL S
     *TORAGE MODE *.,/)
      WRITE(NOUT,20)
   20 FORMAT(1X, 64HA 5 BY 5 SUBMATRIX MAY BE STORED IN THE 25 LOCATIONS
     *  ((A(I,J), ,/,1X,                  62HI=1,5),J=1,5). IT IS POSSIB
     *LE TO PASS THIS 5 BY 5 SUBMATRIX TO,/,1X,63HAN IMSL ROUTINE EVEN T
     *HOUGH A HAS BEEN DECLARED TO BE 10 BY 20.,/,1X,46HTHIS IS WHERE AD
     *JUSTABLE DIMENSIONING IS USED.,//,1X,63HSUPPOSE THAT THIS 5 BY 5 S
     *UBMATRIX IS INITIALIZED, N IS SET TO ,/,1X,64H5 AND IA IS SET TO 1
     *0 (THE ROW DIMENSION OF A). THEN THE FOLLOW-,/,1X,64HING CALL STAT
     *EMENT WOULD CAUSE A TO BE PASSED TO SUBROUTINE SUBR,/,1X,10HCORREC
     *TLY.,/)
      WRITE (NOUT,25)
   25 FORMAT(11X,18HDIMENSION A(10,20),/,11X,5HIA=10,/,11X,3HN=5,/,21X,3
     *4H(INITIALIZE 5 BY 5 SUBMATRIX OF A),/,11X,17HCALL SUBR(A,IA,N),//
     *,1X,46HTHE FOLLOWING STATEMENTS WOULD APPEAR IN SUBR,,//,11X,23HSU
     *BROUTINE SUBR(A,IA,N),/,11X,17HDIMENSION A(IA,N),/,16X,1H.,/,16X,1
     *H.,/,16X,1H.,/,11X,3HEND,//,1X,59HIT IS IN THIS MANNER THAT MANY I
     *MSL SUBROUTINES UTILIZE THE,/,1X,61HFORTRAN ADJUSTABLE ARRAY FEATU
     *RE. THE DOCUMENTATION FOR SUCH ,/, 1X,59HSUBROUTINES REFER TO A AS
     * A MATRIX, N AS THE ORDER OF A (OR,/,1X,63HTHE NUMBER OF ROWS IN A
     *), AND IA AS THE ROW DIMENSION OF MATRIX,/,1X,64HA EXACTLY AS SPEC
     *IFIED IN THE DIMENSION STATEMENT IN THE CALLING )
      WRITE (NOUT,30)
   30 FORMAT(1X,64HPROGRAM. IF THE MATRIX IS NOT SQUARE THEN ANOTHER ARG
     *UMENT, M,  ,/,1X,63HIS REQUIRED TO SPECIFY THE NUMBER OF COLUMNS I
     *N A. THE SECOND  ,/, 1X,59HDIMENSION BOUND, 20 IN THIS EXAMPLE, IS
     * NOT REQUIRED BY THE,/,1X,62HSUBROUTINE AND OFTEN THE DIMENSION ST
     *ATEMENT FOR A IN THE IMSL,/,1X,64HSUBROUTINE USES 1 (I.E., DIMENSI
     *ON A(IA,1)). IN THIS CASE, IT IS,/,1X,60HUNDERSTOOD THAT THE SUBRO
     *UTINE MAY REFERENCE AS MANY COLUMNS,/,1X,64HAS SPECIFIED BY THE DO
     *CUMENT. THE DIMENSION STATEMENT FOR A IN  ,/,1X,47HTHE CALLING PRO
     *GRAM MUST DECLARE A ACCORDINGLY.,//, 1X,61HOTHER STORAGE MODES ARE
     * USED BY SOME IMSL LIBRARY SUBROUTINES,/,1X,61HIN ORDER TO CONSERV
     *E COMPUTER MEMORY. THESE ARE DESCRIBED IN ,/,1X,23HTHE FOLLOWING S
     *ECTIONS.  /)
      WRITE (NOUT,35)
   35 FORMAT(1X,22HSYMMETRIC STORAGE MODE,//,1X,58HA SYMMETRIC MATRIX HA
     *S THE PROPERTY THAT A(I,J)=A(J,I) AND,/,1X,59HSYMMETRIC STORAGE MO
     *DE REPRESENTS SUCH MATRICES AS VECTORS.,/, 1X,59HONLY THE ELEMENTS
     * ON AND BELOW THE MAIN DIAGONAL ARE STORED,/,1X,10H(BY ROWS).,//,1
     *X,64HTHE ORDER AND OCCURRENCE OF THESE ELEMENTS IN MEMORY ARE AS F
     *OL-,/, 1X,63HLOWS (ASSUMING  A  IS A SYMMETRIC MATRIX AND  B  IS A
     * VECTOR). ,//,15X,45HA   A   A             A                     A
     *  ,/,15X,47H 11  12  13            11                    11,//,7X,
     *61HA =     A   A   A       =     A   A           =     A     = B,
     */,15X,47H 21  22  23            21  22                21,//,15X,45
     *HA   A   A             A   A   A             A,/,15X,47H 31  32  3
     *3            31  32  33            22,//,59X,1HA,/,60X,2H31,//,59X
     *,1HA,/,60X,2H32,//,59X,1HA,/,60X,2H33,/   )
      WRITE (NOUT,40)
   40 FORMAT(1X,65HAN N BY N MATRIX IN SYMMETRIC STORAGE MODE IS REDUCED
     * TO A VECTOR,/,1X,64HOF LENGTH N(N+1)/2 WHERE THE ELEMENT IJ CAN B
     *E FOUND AS THE ELE-,/,1X,69HMENT K OF THE VECTOR B, WHERE K=(I(I-1
     *)/2)+J FOR I.GE.J. FOR I.LT.J, ,/,    1X,64HTHE ELEMENT IJ IS IDEN
     *TICAL TO THE ELEMENT JI. STORING A MATRIX ,/, 1X,62HIN THIS MANNER
     * EFFECTS A SAVINGS OF N(N-1)/2 MEMORY LOCATIONS.,//,1X,36HBAND AND
     * BAND SYMMETRIC STORAGE MODE,//,1X,62HAN N BY N BAND MATRIX WITH K
     * LOWER CODIAGONALS AND J UPPER CO-,/,1X,63HDIAGONALS STORED IN BAN
     *D STORAGE MODE IS REDUCED TO A MATRIX OF,/,1X,65HDIMENSION N BY (K
     *+J+1). THE MATRIX IS STORED ROWWISE SO THAT THE ,/,1X,64HZERO ELEM
     *ENTS ARE COMPRESSED OUT OF THE MATRIX AND THE MAIN DIA-,/,1X,63HGO
     *NAL ELEMENTS FALL IN COLUMN K+1. FOR EXAMPLE, THE 5 BY 5 BAND,/,1X
     *,63HMATRIX A, WITH 1 LOWER AND 2 UPPER CODIAGONALS, WOULD BE STORE
     *D,/,1X,48HIN BAND STORAGE MODE IN MATRIX B AS SHOWN BELOW.,/)
      WRITE (NOUT,50)
   50 FORMAT(11X,43HA   A   A   0   0             0   A   A   A,/,11X,45
     *H 11  12  13                        11  12  13,//,11X,43HA   A   A
     *   A   0             A   A   A   A,/,11X,21H 21  22  23  24      ,
     *24H          21  22  23  24,//,3X,28HA =     0   A   A   A   A   ,
     *33H    =     A   A   A   A       = B,/,11X,19H     32  33  34  35,
     *26H            32  33  34  35,
     *                      //,   11X,43H0   0   A   A   A             A
     *   A   A   0,/,11X,41H         43  44  45            43  44  45,
     *  /,   /,11X,43H0   0   0   A   A             A   A   0   0,/,11X,
     *45H             54  55            54  55        ,/   )
      WRITE (NOUT,55)
   55 FORMAT(1X,63HAN N BY N SYMMETRIC BAND MATRIX WITH K UPPER AND K LO
     *WER CODIA-,/,1X,60HGONALS STORED IN BAND SYMMETRIC STORAGE MODE IS
     * REDUCED TO A,/,1X,62HMATRIX OF DIMENSION N BY (K+1). ONLY THE ELE
     *MENTS ON THE MAIN ,/,1X,59HDIAGONAL AND THE K SUB-DIAGONALS ARE ST
     *ORED. THE MATRIX IS ,/,1X,64HSTORED ROWWISE SO THAT THE MAIN DIAGO
     *NAL ELEMENTS FALL IN COLUMN,/, 1X,4HK+1.,//,1X,64HFOR EXAMPLE, THE
     * 5 BY 5 BAND SYMMETRIC MATRIX A WITH 1 UPPER AND,/,1X,63HLOWER COD
     *IAGONAL WOULD BE STORED IN SYMMETRIC BAND STORAGE MODE ,/,1X,27HIN
     * MATRIX B AS SHOWN BELOW.,/)
      WRITE (NOUT,60)
   60 FORMAT( 11X,35HA   A   0   0   0             0   A  ,/,11X, 37H 11
     *  12                            11,//,    11X,35HA   A   A   0   0
     *            A   A  ,/,11X,37H 21  22  23                    21  22
     *,//,3X,54HA  =    0   A   A   A   0       =     A   A       =  B,/
     *, 11X,37H     32  33  34                32  33,//,11X,35H0   0   A
     *   A   A             A   A,/,11X,28H         43  44  45         ,
     *9H   43  44,//,11X,35H0   0   0   A   A             A   A,/,11X,
     *37H             54  55            54  55,//,
     *1X,22HHERMITIAN STORAGE MODE,//,1X,62HAN N BY N HERMITIAN MATRIX S
     *TORED IN HERMITIAN STORAGE MODE IS,/,1X,60HREDUCED TO A COMPLEX VE
     *CTOR WITH N(N+1)/2 COMPLEX LOCATIONS.,/,1X,64HONLY THE ELEMENTS ON
     * OR BELOW THE MAIN DIAGONAL OF THE HERMITIAN,/,1X,64HMATRIX ARE ST
     *ORED (BY ROWS). HERMITIAN STORAGE MODE FOR COMPLEX ,/,1X,66HMATRIC
     *ES IS ANALOGOUS TO SYMMETRIC STORAGE MODE FOR REAL MATRICES.,/,1X,
     *48HSEE THE SECTION ABOVE ON SYMMETRIC STORAGE MODE.)
      RETURN
      END

