C   IMSL ROUTINE NAME   - UHELP1
C
C-----------------------------------------------------------------------
C
C   LATEST REVISION     - JUNE 1, 1981
C
C   PURPOSE             - WRITE INFORMATION REGARDING IMSL
C                           CONVENTIONS AND NOTATION TO AN OUTPUT
C                           FILE
C
C   USAGE               - CALL UHELP1
C
C   REQD. IMSL ROUTINES - UGETIO
C
C   NOTATION            - INFORMATION ON SPECIAL NOTATION AND
C                           CONVENTIONS IS AVAILABLE IN THE MANUAL
C                           INTRODUCTION OR THROUGH IMSL ROUTINE UHELP
C
C   REMARKS      IF THE USER DESIRES THAT OUTPUT BE WRITTEN TO A DEVICE
C                OTHER THAN THE STANDARD OUTPUT DEVICE, HE MUST FIRST
C                CALL IMSL ROUTINE UGETIO TO RESET THE OUTPUT DEVICE.
C                SEE THE UGETIO DOCUMENT.
C
C-----------------------------------------------------------------------
C
      SUBROUTINE UHELP1
C                                  SPECIFICATIONS FOR LOCAL VARIABLES
      INTEGER            IOPT,NIN,NOUT
C                                  FIRST EXECUTABLE STATEMENT
      IOPT = 1
      CALL UGETIO (IOPT,NIN,NOUT)
      WRITE(NOUT,5)
    5 FORMAT(1X,14(1H ),38HDOCUMENTATION CONVENTIONS AND NOTATION,//,1X,
     *64HDOCUMENTATION IS WRITTEN IN A MANNER WHICH ALLOWS IT TO BE INDE
     *-/1X,59HPENDENT OF SPECIFIC COMPUTER-COMPILER ENVIRONMENTS WHENEVE
     *R,/,1X,67HPOSSIBLE. BUT WHEN IT IS NECESSARY, ENVIRONMENT SPECIFIC
     * STATEMENTS ,/,1X,10HARE MADE. ,//)
      WRITE(NOUT,10)
   10 FORMAT(1X,52HTHE PRECISION OF A CODE MAY BE SINGLE FOR ONE SET OF,
     *7H COMPU-,/,1X,47HTERS AND DOUBLE FOR ANOTHER. IN SUCH CASES, THE,
     *20H PRECISION/HARDWARE ,/, 1X,59HSTATEMENT IN THE DOCUMENT SPECIFI
     *ES THE VARIOUS SETS OF EN-,/,1X,11HVIRONMENTS.//)
      WRITE(NOUT,15)
   15 FORMAT(1X,54(1H ),8HHARDWARE,                        /,1X,6(1H ),6
     *3HCOMPUTER                     NAME              DESCRIPTOR      ,
     */,1X,67H      --------                     ----              -----
     *-----    ,//)
      WRITE(NOUT,20)
   20 FORMAT(
     *59H IBM 360/370/43XX/30XX SERIES       IBM                 H32,/,
     *59H      AND COMPATABLE MAINFRAMES                            ,/,
     *59H      (I.E.,AMDAHL,ETC.)                                   ,/,
     *59H SIEMENS 7.7XX                      SIEMEN              H32,/,
     *59H XEROX 530, 560 AND SIGMA 5-9       XEROX               H32,/,
     *59H DATA GENERAL ECLIPSE/NOVA          DGC                 H32,/,
     *59H DIGITAL EQUIPMENT PDP-11 SERIES    DEC11               H32,/,
     *59H DIGITAL EQUIPMENT VAX-11 SERIES    VAX                 H32,/,
     *59H HEWLETT PACKARD 3000               HP3000              H32,/,
     *59H PRIME 300/400/500,50 SERIES        PRIME               H32,/,
     *59H PERKIN-ELMER 32 BIT SERIES         PERKEL              H32,/)
      WRITE(NOUT,25)
   25 FORMAT(
     *59H UNIVAC 1100 SERIES                 UNIVAC              H36,/,
     *59H HONEYWELL AND CII BULL 6000,       HIS                 H36,/,
     *59H      66, 68 AND DPS8 SERIES                               ,/,
     *59H DIGITAL EQUIPMENT SYSTEM           DEC10               H36,/,
     *59H      10 AND 20                                            ,/,
     */,
     *59H BURROUGHS 6700/7700 SERIES         BGH                 H48,/,
     */,
     *59H CONTROL DATA 6000/7000,            CDC                 H60,/,
     *59H      CYBER 70/170 SERIES                                  ,/)
      WRITE(NOUT,30)
   30 FORMAT(  1X,61HA REFERENCE TO H32 APPLIES TO ALL OF THE ABOVE COMP
     *UTERS THAT, 1X,/,64H HAVE H32 AS THEIR HARDWARE DESCRIPTOR. WHEN I
     *NFORMATION IS COM-, /, 1X,61HPUTER DEPENDENT, THE COMPUTER NAME IS
     * USED. FOR EXAMPLE, THE ,/,  1X,64HFOLLOWING PRECISION/HARDWARE ST
     *ATEMENT INDICATES THAT THE DOUBLE,/,    1X,63HPRECISION CODE IS AV
     *AILABLE ON ALL COMPUTERS THAT HAVE H32 AS  ,/,  1X,63HTHEIR HARDWA
     *RE DESCRIPTOR. THE SINGLE PRECISION VERSION IS PRO-,/,  1X,21HVIDE
     *D FOR ALL OTHERS.,//,  1X,43H     C   PRECISION/HARDWARE    - DOUB
     *LE/H32,/ ,1X,52H                               - SINGLE/H36,H48,H6
     *0 //)
      WRITE(NOUT,35)
   35 FORMAT(  1X,64HALL OTHER DOCUMENTATION FOR SUCH CODES IS WRITTEN F
     *OR THE SINGLE,/, 1X,63HPRECISION VERSION, WITH THE UNDERSTANDING T
     *HAT CERTAIN OBVIOUS , /,  1X,64HACTIONS MUST BE TAKEN WHEN THE SPE
     *CIFIC USER ENVIRONMENT IS ONE /,  1X,58HIN THE DOUBLE PRECISION SE
     *T. THESE ACTIONS ARE AS FOLLOWS.,//,  1X,63H-  ALL NON-INTEGER ARG
     *UMENTS MUST APPEAR IN APPROPRIATE, DOUBLE,/,  4X,59HPRECISION FORM
     *, TYPE STATEMENTS IN THE CALLING PROGRAM (UN-,/   4X,60HLESS SPECI
     *FIC INSTRUCTIONS TO THE CONTRARY ARE GIVEN IN THE ,/,  4X,10HDOCUM
     *ENT.),//,   1X,63H-  DOCUMENT EXAMPLES MUST BE CONVERTED TO DOUBLE
     * PRECISION FORM,/, 1X,63H   BY CHANGING TYPE STATEMENTS, CONSTANTS
     *, AND BASIC EXTERNAL  ,/,  4X,58HFUNCTION NAMES TO THE CORRESPONDI
     *NG DOUBLE PRECISION FORM.,//)
      WRITE(NOUT,40)
   40 FORMAT(  1X,64HSOME IMSL ROUTINE NAMES ARE NOT THE SAME AS THE NAM
     *E OF THE COR-,/,   1X,64HRESPONDING DOCUMENT PAGE. IN THESE CASES,
     * THE NOTATION P=R IS   ,/, 1X,62HUSED TO MEAN THAT ROUTINE R IS DO
     *CUMENTED ON REFERENCE MANUAL ,/,  1X,62HPAGE P. FOR EXAMPLE, MERF=
     *ERF IMPLIES THAT THE ROUTINE NAME IS,/,  1X,63HERF AND THAT DOCUME
     *NTATION FOR ERF IS LOCATED ON REFERENCE MAN-,/,  1X,14HUAL PAGE ME
     *RF.)
      RETURN
      END

