#! /bin/bash
# import : TMPDIR

expname=L60CGW
expcode=uanuj
EXTCTL1=5      ### CONTROLLED FOR SPLITTING - 1
EXTCTL2=5      ### CONTROLLED FOR SPLITTING - 2
YYYY1=1993
YYYY2=1993
M1=$EXTCTL1
M2=$EXTCTL2
#== Parameter 1 - CASE ===========================
P101=( s EXPNAME  $expcode )
P104=( n HH  00  8 ) # should be 0 # starting time [UTC] and frequency [/day]
P105=( n REFDATE  1941  12  1 )
P106=( n OPT_30D  1 )
#== Parameter 2 - SOURCE =========================
P201=( n NC_DC  60  1. )  # 120  0.5
P202=( n PHI0_DPHI  45  90 )                       # integer
P203=( n CFACTOR  125. )
#P203=( n CFACTOR  1989.0 )   #  230.3 / 1989.  for 2005.11
#P203=( n CFACTOR  1419.0 )   #  169.1 / 1419.  for 1993.05
P204=( n NZ_SRC  -999 )
P205=( n LAT_RNG  -10.0  10.0 )
#== Parameter 3 - BACKGROUND =====================
P301=( n BETA_WM  0.8 )   # def: 2.0 ??  /  0.8 for hg2ac
P302=( n NX_B0  360 )
P303=( n NZ_B  60 )
P304=( n NK_B  90 )
#== Parameter 9 - I/O ============================
P901=( n DAY1  1 )                 # the earlist date-of-file among input files
P902=( n NDAY_I  3 )               # number of days in one input file
P903=( n MISSV  0. )
P990=( s FID  pc  pc  pa  pa  pc )
P991=( s FILE_I_HEAD  "/hippo0/HG2AMIP/$expname" )
P992=( s FILE_I_FORM  XXXX/${P101[2]}a.XXXX_XXXXXXXXXXXX00.nc  -999 )
P993=( s FILE_I_XXXX  FID              FID  YYYY MM  DD        -999 )
P994=( s VAR_I_NAME  dch_max  vars_cgw  u  v  indic_mc )
P995=( s FILE_I_HEAD2  "/data11/kyh/analy/cgwp_offline/ERA-I_eq" )
#P996=( s FILE_I_FORM2  era-interim_eq_2005-11-01_XXXX.dat  -999 )
#P997=( s FILE_I_XXXX2                            VAR_I_N   -999 )
P996=( s FILE_I_FORM2  era-interim_eq_XXXX-XXXX-01_XXXX.dat  -999 )
P997=( s FILE_I_XXXX2                 YYYY  MM     VAR_I_N   -999 )
P998=( s VAR_I_NAME2  u  v  t )
P980=( s FILE_ALT  "/hippo0/HG2AMIP/$expname/invariant/L60_z.nc" )
P981=( s VAR_ALT  ht  ht_1 )  # z_theta, z_rho
P999=( s FILE_O  '' )
#=================================================
P102=( n YYYY  '' )
P103=( n MM  ''  1 )               # starting month and number of months per year

F_SOURCE='offline_hg2_ra'
F_NAMELIST="$TMPDIR/namelist/namelist.$F_SOURCE-$$"
F_LOG="log/log.$F_SOURCE-$$"

#== Functions ====================================
. $UTIL/shell/cr_namelist.sh
. $UTIL/shell/ex_date_umstr.sh

#== Body =========================================

YYYY=$YYYY1  ;  while [ $YYYY -le $YYYY2 ] ; do
M=$M1        ;  while [ $M    -le $M2    ] ; do

  MM=$(( M ))  ;  if [ $M -lt 10 ] ; then MM="0$MM" ; fi
  P102[2]=$YYYY
  P103[2]=$MM
#  ODIR=$DATD/$expname/dchm_pdf/$YYYY
  ODIR=/data11/kyh/analy/cgwp_offline
  P999[2]="$ODIR/${P101[2]}_ra.cgwp_offline.$YYYY.${MM}_rescale_1.nc"
  if [ ! -d $ODIR ] ; then mkdir -p $ODIR ; fi
#  [ -e ${P999[2]} ] && mv ${P999[2]} $ODIR/old.${P101[2]}.dchm-midlev_pdf.$YYYY.${MM}.nc

  # create namelist --------------------
  cr_file $F_NAMELIST
  cr_nl $F_NAMELIST ANALCASE "${P101[*]}" "${P102[*]}" "${P103[*]}" "${P104[*]}" "${P105[*]}" "${P106[*]}"
  cr_nl $F_NAMELIST PARAM_S "${P201[*]}" "${P202[*]}" "${P203[*]}" "${P204[*]}" "${P205[*]}"
  cr_nl $F_NAMELIST PARAM_B "${P301[*]}" "${P302[*]}" "${P303[*]}" "${P304[*]}"
  cr_nl $F_NAMELIST FILEIO "${P901[*]}" "${P902[*]}" "${P903[*]}" "${P990[*]}" "${P991[*]}" "${P992[*]}" "${P993[*]}" "${P994[*]}" "${P995[*]}" "${P996[*]}" "${P997[*]}" "${P998[*]}" "${P999[*]}" "${P980[*]}" "${P981[*]}"
  cat $F_NAMELIST

  # compile and run --------------------
  comnrun2 $F_SOURCE $F_NAMELIST # &> $F_LOG
  echo "pid : $$"

M=$(( $M+1 ))
done
YYYY=$(( $YYYY+1 ))
done

#== End ==========================================
exit 0

