#
#FC = $(FC_DBG) # -mcmodel=medium -shared-intel
RM = rm -f
NCINC ?= $(NETCDF)/include
NCLIB ?= $(NETCDF)/lib
NCLIBNAME ?= -lnetcdf -lnetcdff
LIB_FFTPACK ?= $(UTIL)/num_analysis/FFT/fftpack5.1/$(VER_COMP)/lib/libfftpack.a

EXEC_ALL := tem_ra tem_ra-lastmiss tem_qg tem_qg_betap_gp epf_fc2_ra sepa_epf epfsa0_fc2_ra epfsa1_fc2_ra sepa_epfsa sepa_epfsa-a sepa_epfsa1 sepa_epfsa2
MOD_N := m_reanal netio
MOD_N := $(MOD_N) fft tem epf warc3d
SUB_N := fdcoef

MOD_F = $(addsuffix .f90,$(MOD_N))
MOD_O = $(MOD_F:.f90=.o)
SUB_F = $(addsuffix .f90,$(SUB_N))
SUB_O = $(SUB_F:.f90=.o)

ALL_SUB_F = $(MOD_F) $(SUB_F)
ALL_SUB_O = $(MOD_O) $(SUB_O)

LIB_SUBS = libsubs.a


# main

tem_ra:	tem_ra.f90  $(LIB_SUBS) c_phys.inc
		$(FC) $< -o $@ $(LIB_SUBS) $(LIB_FFTPACK) -L$(NCLIB) $(NCLIBNAME)

tem_ra-lastmiss:	tem_ra-lastmiss.f90  $(LIB_SUBS) c_phys.inc
		$(FC) $< -o $@ $(LIB_SUBS) $(LIB_FFTPACK) -L$(NCLIB) $(NCLIBNAME)

tem_qg:	tem_qg.f90  $(LIB_SUBS) c_phys.inc
		$(FC) $< -o $@ $(LIB_SUBS) $(LIB_FFTPACK) -L$(NCLIB) $(NCLIBNAME)

tem_qg_betap_gp:	tem_qg_betap_gp.f90  $(LIB_SUBS) c_phys.inc
		$(FC) $< -o $@ $(LIB_SUBS) $(LIB_FFTPACK) -L$(NCLIB) $(NCLIBNAME)

epf_fc2_ra:	epf_fc2_ra.f90  $(LIB_SUBS) c_phys.inc
		$(FC) $< -o $@ $(LIB_SUBS) $(LIB_FFTPACK) -L$(NCLIB) $(NCLIBNAME)

sepa_epf:	sepa_epf.f90 $(LIB_SUBS)
		$(FC) $< -o $@ $(LIB_SUBS) $(LIB_FFTPACK) -L$(NCLIB) $(NCLIBNAME)

epfsa0_fc2_ra:	epfsa0_fc2_ra.f90 $(LIB_SUBS) c_phys.inc
		$(FC) $< -o $@ $(LIB_SUBS) $(LIB_FFTPACK) -L$(NCLIB) $(NCLIBNAME)

epfsa1_fc2_ra:	epfsa1_fc2_ra.f90 $(LIB_SUBS) c_phys.inc
		$(FC) $< -o $@ $(LIB_SUBS) $(LIB_FFTPACK) -L$(NCLIB) $(NCLIBNAME)

sepa_epfsa:	sepa_epfsa.f90 $(LIB_SUBS)
		$(FC) $< -o $@ $(LIB_SUBS) $(LIB_FFTPACK) -L$(NCLIB) $(NCLIBNAME)

sepa_epfsa-a:	sepa_epfsa-a.f90 $(LIB_SUBS)
		$(FC) $< -o $@ $(LIB_SUBS) $(LIB_FFTPACK) -L$(NCLIB) $(NCLIBNAME)

sepa_epfsa1:	sepa_epfsa1.f90 $(LIB_SUBS)
		$(FC) $< -o $@ $(LIB_SUBS) $(LIB_FFTPACK) -L$(NCLIB) $(NCLIBNAME)

sepa_epfsa2:	sepa_epfsa2.f90 $(LIB_SUBS)
		$(FC) $< -o $@ $(LIB_SUBS) $(LIB_FFTPACK) -L$(NCLIB) $(NCLIBNAME)

# modules

$(LIB_SUBS):	$(ALL_SUB_F)
		$(FC) -c -I$(NCINC) $(ALL_SUB_F)
		ar -rv $@ $(ALL_SUB_O)
		rm -f $(ALL_SUB_O)

# clean

clean:	
		$(RM) $(EXEC_ALL) *.a *.o *.mod

