MODULE CommonData
!
   USE Base, ONLY: i4, r8
!
   IMPLICIT NONE
!
   PRIVATE
!
   INTEGER(i4), PARAMETER, PUBLIC :: NDAT = 101
   INTEGER(i4), PARAMETER, PUBLIC :: NUMP = 6
   INTEGER(i4), PARAMETER, PUBLIC :: NUMQ = 11
   INTEGER(i4), PARAMETER, PUBLIC :: NCOF = NUMP+NUMQ
   INTEGER(i4),            PUBLIC :: nfev, njev
!
   REAL(r8), PARAMETER, PUBLIC :: SMAX = 5._r8
   REAL(r8), PARAMETER, PUBLIC :: DS = 2._r8 * SMAX / (NDAT-1)
   REAL(r8), DIMENSION(NDAT), PUBLIC :: s, fs
!
END MODULE CommonData
