#! /bin/bash

TMPDIR=${TMPDIR:-"~/tmp"}
if [ ! -d $TMPDIR/exec ] ; then mkdir -p $TMPDIR/exec ; fi

if [ $# -eq 0 ] ; then
  echo -e "\n Usage:  $0 (0/1/2) [source file] (arguments)\n"
  echo -e " --> 1) Compile [source file]"
  echo -e " --> 2) exec/run_[source file].$$ (arguments)\n"
  exit 1
fi

l_comp=1 ; l_run=1
case "$1" in
  '0')  shift             ;;
  '1')  l_run=0  ; shift  ;;
  '2')  l_comp=0 ; shift  ;;
esac

src=$1 ; shift
arg=( $@ )
exe=run_$src.$$
tmpstr=$( nc-config --version )
COMPBASE_D=${VER_COMP}_nc${tmpstr#"netCDF "}

if [ $l_comp -eq 1 ] ; then
  echo '========================================='
  echo ' Compile starts'

  # compile
  cd COMPILE
  while [ -e $COMPBASE_D/COMPILING_NOW ] ; do
    echo ' Other program has been compiled. Sleep 5 sec.' ; sleep 5
  done
  [ -d $COMPBASE_D ] || mkdir -p $COMPBASE_D
  touch $COMPBASE_D/COMPILING_NOW
  make $src
  if [ $? -ne 0 ] ; then
    rm -f $COMPBASE_D/COMPILING_NOW
    echo "COMPILE ERROR : $src"
    echo "== STOP ================================="
    exit 1
  fi
  cd ..
else
  if [ ! -x COMPILE/$COMPBASE_D/bin/$src ] ; then echo ' No execution file.' ; exit 2 ; fi
fi

if [ $l_run -eq 1 ] ; then
  [ -e $TMPDIR/exec/$exe ] && rm -f $TMPDIR/exec/$exe
  cp COMPILE/$COMPBASE_D/bin/$src $TMPDIR/exec/$exe
fi

if [ $l_comp -eq 1 ] ; then
  rm -f COMPILE/$COMPBASE_D/COMPILING_NOW
  echo '-----------------------------------------'
  echo ' Compile ends'
  echo '========================================='
fi

if [ $l_run -eq 1 ] ; then
  echo ' Run'
  echo '-----------------------------------------'
  echo "> $exe ${arg[@]}"
  $TMPDIR/exec/$exe ${arg[@]}
  if [ $? -ne 0 ] ; then
    echo "EXECUTION ERROR : $exe ${arg[@]}"
    echo "== STOP ================================="
    exit 2
  fi
  rm -f $TMPDIR/exec/$exe
fi

echo

exit 0

